export const ERROR_CODES: Record<number, string> = {
	701: 'Low pressure fault - Please call installer',
	702: 'Low pressure lock - Auto RESET',
	703: 'Frost protection - Please call installer',
	704: 'Hot gas fault - Reset in hh:mm',
	705: 'Motor protection VEN - Please call installer',
	706: 'Motor protection BSUP - Please call installer',
	707: 'Coding WP - Please call installer',
	708: 'Sensor return - Please call installer',
	709: 'Sensor supply - Please call installer',
	710: 'Sensor hot gas - Please call installer',
	711: 'Sensor outside temp. - Please call installer',
	712: 'Sensor hot water - Please call installer',
	713: 'Sensor heat source in - Please call installer',
	714: 'Hot gas HW - Reset in hh:mm',
	715: 'High pressure switch-off - Auto RESET',
	716: 'High pressure fault - Please call installer',
	717: 'Flow heat source - Please call installer',
	718: 'Max. outside temp. - Auto RESET',
	719: 'Min. outside temp. - Auto RESET',
	720: 'Heat source temp. - Auto RESET in hh:mm',
	721: 'Low pressure switch-off - Auto RESET',
	722: 'Temp. diff. heating water - Please call installer',
	723: 'Temp. diff. hot water - Please call installer',
	724: 'Temp. diff. defrost - Please call installer',
	725: 'System fault HW - Please call installer',
	726: 'Sensor mixing circuit 1 - Please call installer',
	727: 'Brine pressure - Please call installer',
	728: 'Sensor heat source out - Please call installer',
	729: 'Rotary field fault - Please call installer',
	730: 'Power heating out - Please call installer',
	732: 'Cooling fault - Please call installer',
	733: 'Anode fault - Please call installer',
	734: 'Anode fault - Please call installer',
	735: 'Sensor ext. energy source - Please call installer',
	736: 'Sensor solar collector - Please call installer',
	737: 'Sensor solar buffer - Please call installer',
	738: 'Sensor mixing circuit 2 - Please call installer',
	750: 'Sensor ext. return - Please call installer',
	751: 'Phase monitor fault',
	752: 'Phase monitor / Flow fault',
	755: 'Connection to slave lost - Please call installer',
	756: 'Connection to master lost - Please call installer',
	757: 'LP fault HW device',
	758: 'Defrost fault',
	759: 'TDI message',
	760: 'Defrost fault',
	761: 'LIN connection interrupted',
	762: 'Sensor suction compressor',
	763: 'Sensor suction evaporator',
	764: 'Sensor compressor heating',
	765: 'Overheating',
	766: 'Operating limits compressor',
	767: 'STB electrical heater',
	770: 'Low overheating',
	771: 'High overheating',
	776: 'Operating limits compressor',
	777: 'Expansion valve',
	778: 'Sensor low pressure',
	779: 'Sensor high pressure',
	780: 'Sensor EVI',
	781: 'Sensor liquid, before Ex-valve',
	782: 'Sensor EVI suction gas',
	783: 'Communication SEC-Inverter',
	784: 'VSS locked',
	785: 'SEC-Board defective',
	786: 'Communication SEC-Inverter',
	787: 'Compressor alarm',
	788: 'Severe inverter fault',
	789: 'LIN/Coding missing',
	790: 'Severe inverter fault',
	791: 'ModBus connection lost',
	792: 'LIN connection interrupted',
	793: 'Severe inverter fault',
	'-1': 'Unknown error',
};

export const OUTAGE_CODES: Record<number, string> = {
	'-1': 'Unknown outage',
	0: 'Heat pump fault',
	1: 'System fault',
	2: 'Operating mode second heat generator',
	3: 'Utility block',
	4: 'Reset',
	5: 'Defrosting (air/water devices only)',
	6: 'Temperature operating limit max',
	7: 'Temperature operating limit min',
	8: 'Lower operating limit',
	9: 'No demand',
};

// ==========================================
// TRANSLATED STATE STRINGS (i18n)
// ==========================================

export const STATE_LINE_1: Record<string, Record<number, string>> = {
	en: {
		0: 'Heat pump running',
		1: 'Heat pump idle',
		2: 'Heat pump coming',
		3: 'Error code',
		4: 'Defrosting',
		5: 'Waiting for LIN connection',
		7: 'Compressor heating up',
		8: 'Pump pre-run',
	},
	de: {
		0: 'Wärmepumpe läuft',
		1: 'Wärmepumpe steht',
		2: 'Wärmepumpe kommt',
		3: 'Fehlercode',
		4: 'Abtauen',
		5: 'Warte auf LIN-Verbindung',
		7: 'Verdichter heizt',
		8: 'Vorlauf Pumpe',
	},
};

export const STATE_LINE_2: Record<string, Record<number, string>> = {
	en: { 0: 'since', 1: 'in' },
	de: { 0: 'seit', 1: 'in' },
};

export const STATE_LINE_3: Record<string, Record<number, string>> = {
	en: {
		0: 'Heating operation',
		1: 'No demand',
		2: 'Grid switch-on delay',
		3: 'Cycle lock',
		4: 'Lock time',
		5: 'Hot water',
		6: 'Info heating out program',
		7: 'Defrosting',
		8: 'Pump pre-run',
		9: 'Thermal disinfection',
		10: 'Cooling operation',
		12: 'Swimming pool / Photovoltaics',
		13: 'Heating ext. energy source',
		14: 'Hot water ext. energy source',
		16: 'Flow monitoring',
		17: 'Second heat generator 1 operation',
	},
	de: {
		0: 'Heizbetrieb',
		1: 'Kein Bedarf',
		2: 'Netz-Einschaltverzögerung',
		3: 'Schaltspielsperre',
		4: 'Sperrzeit',
		5: 'Warmwasser',
		6: 'Info Estrichtrocknung',
		7: 'Abtauen',
		8: 'Vorlauf Pumpe',
		9: 'Thermische Desinfektion',
		10: 'Kühlbetrieb',
		12: 'Schwimmbad / PV',
		13: 'Heizen ext. Quelle',
		14: 'Warmwasser ext. Quelle',
		16: 'Durchflussüberwachung',
		17: 'Zweiter Erzeuger 1',
	},
};

export const STATE_HEATING: Record<string, Record<number, string>> = {
	en: { 0: 'Reduced', 1: 'Normal', 2: 'Heating limit', 3: 'Off', 4: 'Frost protection' },
	de: { 0: 'Abgesenkt', 1: 'Normal', 2: 'Heizgrenze', 3: 'Aus', 4: 'Frostschutz' },
};

export const HP_TYPES: Record<number, string> = {
	0: 'ERC',
	1: 'SW1',
	2: 'SW2',
	3: 'WW1',
	4: 'WW2',
	5: 'L1I',
	6: 'L2I',
	7: 'L1A',
	8: 'L2A',
	9: 'KSW',
	10: 'KLW',
	11: 'SWC',
	12: 'LWC',
	13: 'L2G',
	14: 'WZS',
	15: 'L1I407',
	16: 'L2I407',
	17: 'L1A407',
	18: 'L2A407',
	19: 'L2G407',
	20: 'LWC407',
	21: 'L1AREV',
	22: 'L2AREV',
	23: 'WWC1',
	24: 'WWC2',
	25: 'L2G404',
	26: 'WZW',
	27: 'L1S',
	28: 'L1H',
	29: 'L2H',
	30: 'WZWD',
	31: 'ERC',
	40: 'WWB_20',
	41: 'LD5',
	42: 'LD7',
	43: 'SW 37_45',
	44: 'SW 58_69',
	45: 'SW 29_56',
	46: 'LD5 (230V)',
	47: 'LD7 (230 V)',
	48: 'LD9',
	49: 'LD5 REV',
	50: 'LD7 REV',
	51: 'LD5 REV 230V',
	52: 'LD7 REV 230V',
	53: 'LD9 REV 230V',
	54: 'SW 291',
	55: 'LW SEC',
	56: 'HMD 2',
	57: 'MSW 4',
	58: 'MSW 6',
	59: 'MSW 8',
	60: 'MSW 10',
	61: 'MSW 12',
	62: 'MSW 14',
	63: 'MSW 17',
	64: 'MSW 19',
	65: 'MSW 23',
	66: 'MSW 26',
	67: 'MSW 30',
	68: 'MSW 4S',
	69: 'MSW 6S',
	70: 'MSW 8S',
	71: 'MSW 10S',
	72: 'MSW 13S',
	73: 'MSW 16S',
	74: 'MSW2-6S',
	75: 'MSW4-16',
	76: 'LD2AG',
	77: 'LWD90V',
	78: 'MSW3-12',
	79: 'MSW3-12S',
	80: 'MSW2-9S',
	'-1': 'Unknown type',
};
